### ISSUE TITLE
[BUG] gALCX vault deposit asks for approval again if switching to another tab while awaiting initial approval

### ISSUE THREAD

**Issue by imimim-username** [alchemix-finance/alchemix-v2-frontend#371] opened 2022-08-22 15:54 UTC
### Contact Details

IMIMIM on discord

### What happened?

The following has happened a few times: I'm set to deposit some ALCX into gALCX; I sign the ALCX approval transaction; while awaiting the approval to go through, I'll flip to another tab; and when the approval transaction is complete, I go back to the alchemix tab, but it doesn't recognize that I approved the ALCX deposit, and it asks me to approve again before I deposit. This is using ledger on brave wallet in brave browser.

### Steps to reproduce

1. Navigate to https://alchemix.fi/farms on mainnet
2. In gALCX wrapper box, select the amount of ALCX to wrap
3. Click the 'Wrap' button
4. Wallet presents transaction to approve allowance of ALCX spend before actually wrapping
5. Sign the approval transaction
6. While waiting for transaction to be confirmed, go to another tab to look at stuff
7. After transaction is confirmed, go back to the Alchemix tab
8. Try to wrap approved ALCX, but it's asking to sign approval transaction again before wrapping.
...

### Expected behavior

Normally, when approving tokens to be transacted/wrapped/swapped/etc, one can go about their business in other tabs until the approval transaction is confirmed. Once it's confirmed, one normally doesn't have to re-approved before proceeding with the desired transaction. Meaning, the system somehow knows at that point that the tokens are approved, and doesn't ask for re-approval for something that was already approved. 

Thank you

### What browser were you using?

Brave

**Comment by n4n0GH** [comment] 2022-08-23 14:42
I'm inclined to say that it's a Brave specific issue. Take a look at this: https://github.com/alchemix-finance/alchemix-v2-frontend/blob/prod/src/stores/v2/wrapperActions.ts#L55

When starting the deposit, or stake, the code goes into a try/catch block first. Next it checks if the allowance is less than the amount you want to deposit and if so, initiates an approval transaction. I'm not sure how switching to another tab would disturb this logic because it doesn't require the user to have focus on the site.

If possible, could you try this behaviour in a different browser, like Chrome or Firefox?

**Comment by n4n0GH** [comment] 2022-08-24 15:38
After discussing this issue with OP via DMs in Discord and trying to replicate the issue it seems to have been caused by Brave, as suspected by me. Closing with wontfix.

**Closed as not planned by n4n0GH** 2022-08-24 15:38 UTC
Labels: bug, additional info needed
